"""empty message

Revision ID: 9c1606c2f772
Revises: 7e246705da6a
Create Date: 2022-07-23 08:47:48.918833

"""

# revision identifiers, used by Alembic.
revision = '9c1606c2f772'
down_revision = '7e246705da6a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('URL', sa.Column('protected', sa.Boolean(), nullable=True))
    op.add_column('file', sa.Column('protected', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'protected')
    op.drop_column('URL', 'protected')
    # ### end Alembic commands ###
